---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
  # TODO: enable
  enabled: False
platforms:
  - name: ome-dundeeomero.openmicroscopy.org
    image: centos/systemd
    command: /sbin/init
    privileged: true
    groups:
      - docker-hosts
      - omero-server
      - monitored
provisioner:
  name: ansible
  options:
    diff: true
    skip-tags:
      - skip_molecule
  inventory:
    group_vars:
      all:
        molecule_test: true
      docker-hosts:
        # firewalld isn't installed, don't attempt to disable
        iptables_raw_disable_firewalld: False
  playbooks:
    converge: ../../site.yml
  lint:
    name: ansible-lint
  # env:
  #   ANSIBLE_ROLES_PATH: ../../vendor
scenario:
  name: ome-dundeeomero
  converge_sequence:
    - converge
  test_sequence:
    - destroy
    # dependency must come first so that ansible-lint will see a custom module
    # This might be fixed by https://github.com/ansible/molecule/pull/1739
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    # FIXME: Some tasks are not idempotent
    # - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
