---
# defaults for omero-server

omero_server_release: present

# OMERO database connection parameters
omero_server_dbhost: localhost
omero_server_dbuser: omero
omero_server_dbname: omero
omero_server_dbpassword: omero

# OMERO root password
omero_server_rootpassword: omero

# Dictionary of additional OMERO configuration options
omero_server_config_set: {}

# OMERO system user
omero_server_system_user: omero-server
omero_server_system_user_manage: true

# OMERO system user ID (If not defined one is chosen automatically)
# omero_server_system_uid:

# OMERO system user umask
omero_server_system_umask: "0002"

# system group for the ManagedRepository
omero_server_system_managedrepo_group: omero

# OMERO data directory
omero_server_datadir: /OMERO

# OMERO ManagedRepository directory
omero_server_datadir_managedrepo: "{{ omero_server_datadir }}/ManagedRepository"

# Permissions for OMERO data directories apart from ManagedRepository
omero_server_datadir_mode: "u=rwX,g=rX,o=rX"

# Permissions for OMERO ManagedRepository
omero_server_datadir_managedrepo_mode: "u=rwX,g=srwX,o=rX"

# Setup systemd services
omero_server_systemd_setup: true

# Change the systemd limit for number of open files (default ignore)
omero_server_systemd_limit_nofile:


# Services which OMERO server needs to be running before it can start,
# such as remote storage.
omero_server_systemd_after: []

# Services which OMERO server needs to be concurrently running.
omero_server_systemd_requires: []

# Dictionary of additional environment variables
omero_server_systemd_environment: {}

# List of additional Python packages to be installed into virtualenv
omero_server_python_addons: []

# If non-empty dump the OMERO database to this directory before upgrading
omero_server_database_backupdir: ""

# If true disable anonymous ciphers and use self-signed certificates
omero_server_selfsigned_certificates: true


######################################################################
# Expert users only!
######################################################################

omero_server_ice_version: "3.6"

omero_server_python_requirements_ice_package:
  RedHat:
    9: "https://github.com/glencoesoftware/zeroc-ice-py-rhel9-x86_64/releases/download/\
      20230830/zeroc_ice-3.6.5-cp39-cp39-linux_x86_64.whl"
  Debian:
    22: "https://github.com/glencoesoftware/zeroc-ice-py-ubuntu2204-x86_64/releases/download/\
      20221004/zeroc_ice-3.6.5-cp310-cp310-linux_x86_64.whl"


# TODO: sort this out
# ? pip install omero-server-dependencies=={{omero_server_release}}
# ? get_url https://downloads.openmicroscopy.org/omero/
#     {{omero_server_release}}/artifacts/
#     OMERO.server-{{omero_server_release}}.requirements.txt
# List of Python3 packages to install
# _omero_* are temporary overrides pending a final release
# Can't leave this unset because pip won't install the Python 3 pre-releases
_omero_py_version: '>=5.6.0'
_omero_dropbox_version: '>=5.6.1'
omero_server_python_requirements:
  - omego==0.7.0
  # TODO: make the use of our non-standard wheel optional
  - "{{ omero_server_python_requirements_ice_package[ansible_os_family][
        ansible_distribution_major_version | int ] |
        default('zeroc-ice')}}"
  - "omero-py{{ _omero_py_version | default('') }}"
  - "omero-dropbox{{ _omero_dropbox_version  | default('') }}"
  # TODO: keep or ditch ipython? It's a big dependency and mostly useful for
  # clients
  # - ipython
  - jinja2
  # Includes optional dependencies: always installed but activation may be
  # optional
  - omero-server

# Path to virtualenv
omero_server_virtualenv_basedir: "{{ omero_server_basedir + '/venv3' }}"

# OMERODIR
omero_server_omerodir: "{{ omero_server_basedir }}/{{ omero_server_symlink }}"

# How to run omero
omero_server_omero_command: "{{ omero_server_omerodir }}/bin/omero"

# Config update command
omero_server_config_update: >-
  {{
    omero_server_omero_command + ' load --glob ' + omero_server_basedir +
    '/config/*.omero'
  }}

# Need to set OMERODIR when omego runs omero
omero_server_omego_environment: "{{ {'OMERODIR': omero_server_omerodir} }}"

# Recursively set the owner on the OMERO data directory, use if the directory
# has been copied with an incorrect owner
omero_server_datadir_chown: false

# OMERO BioFormatsCache directory
omero_server_datadir_bioformatscache: >-
  {{ omero_server_datadir }}/BioFormatsCache

# DEVELOPMENT: If True clear the existing configuration before regenerating
omero_server_always_reset_config: true

# DEVELOPMENT: Automatically start systemd omero
omero_server_systemd_start: true

# DEVELOPMENT: Automatically init/upgrade and configure the OMERO database
omero_server_database_manage: true

# DEVELOPMENT: Automatically create and configure OMERO data directories
omero_server_datadir_manage: true

# Base directory for the server installation
omero_server_basedir: "{{ omero_common_basedir }}/server"

# Symlink to the currently installed OMERO.server
omero_server_symlink: OMERO.server

# Path of omego
omero_server_omego: "{{ omero_server_virtualenv_basedir + '/bin/omego' }}"

# Control verbosity of omego
omero_server_omego_verbosity: "-qq"

# Additional omego aguments passed to upgrade or install
omero_server_omego_additional_args: ""

# If True and server is already installed then upgrade to the version in
# omero_server_release, otherwise don't upgrade an existing server.
# This should not be needed if version are correctly compared.
omero_server_upgrade: true

# DEVELOPMENT: Operator for comparing current-version against
# omero_server_release, e.g. '!='. Default is to upgrade when
# current-version < omero_server_release
omero_server_checkupgrade_comparator: '<'


# _omero_server_new_version is set in tasks/omero-install.yml
# We can't just use omero_server_release because if it is "present"
# it needs to be substituted with a value that omego will accept
omero_server_omego_options: >
  --release {{ _omero_server_new_version }}
  --sym {{ omero_server_symlink }}
  --ice {{ omero_server_ice_version }}
  --no-start
  --no-web
  --ignoreconfig
  --omerocli {{ omero_server_virtualenv_basedir + '/bin/omero' }}
  {{ omero_server_omego_verbosity }}
  {{ omero_server_omego_additional_args }}

omero_server_omego_db_options: >
  --dbhost {{ omero_server_dbhost | quote }}
  --dbuser {{ omero_server_dbuser | quote }}
  --dbname {{ omero_server_dbname | quote }}
  --dbpass {{ omero_server_dbpassword | quote  }}
  {{ omero_server_database_manage | ternary('--managedb', '') }}
