---
# Setup systemd files

- name: omero server | systemd service
  become: true
  template:
    dest: /etc/systemd/system/omero-server.service
    force: true
    src: systemd-system-omero-server-service.j2
    mode: 0644
  notify:
    - reload systemd
    - omero-server restart omero-server

# Flush handlers to ensure systemd is reloaded
- name: omero server | flush systemd handlers
  meta: flush_handlers

- name: omero server | enable and start server systemd
  become: true
  service:
    enabled: true
    name: omero-server.service
    state: started
  when: omero_server_systemd_start
