---
galaxy_info:
  role_name: basedeps
  namespace: ome
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Base dependencies for most servers.
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 9
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - cloud
    - system
