---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  # For mysterious reasons naming something "docker" with the current
  # ome-ansible-molecule versions fails
  - name: xdockerx
    image: eniocarboni/docker-rockylinux-systemd:9
    privileged: true
    command: /sbin/init
    groups:
      - docker-hosts
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
  - name: docker-inactive
    image: rockylinux:9
    groups:
      - docker-hosts
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      docker-hosts:
        # This should allow docker-in-docker to work
        docker_storage_driver: vfs
    host_vars:
      xdockerx:
        docker_use_ipv4_nic_mtu: true
        # Latest version 17.12.1.ce-1.el7.centos has a bug that prevents
        # testing on travis: https://github.com/docker/for-linux/issues/219
        #docker_version: 17.09.1.ce-1.el7.centos
      docker-inactive:
        docker_systemd_setup: false
scenario:
  name: default
verifier:
  name: testinfra
