---
- name: Converge
  hosts: all
  roles:
    - role: ome.docker
      docker_additional_options:
        hosts:
          - tcp://127.0.0.1:4243
          - unix:///var/run/docker.sock

  tasks:
    - name: create unprivileged user
      become: true
      user:
        name: test
        state: present
