# Install OMERO.web with a public user on localhost

- hosts: ns-webclients

  roles:

    # Root LV Size
    - role: ome.lvm_partition
      tags: lvm
      lvm_lvname: "{{ provision_root_lvname }}"
      lvm_vgname: "{{ provision_root_vgname }}"
      lvm_lvmount: /
      lvm_lvsize: "{{ provision_rootsize }}"
      lvm_lvfilesystem: "{{ provision_root_filesystem }}"
      when: "not (molecule_test | default(False))"

    - role: ome.ssl_certificate

    - role: ome.nginx

    # OMERO.web configuration in host_vars in different repository
    - role: ome.omero_web
      omero_web_systemd_limit_nofile: 16384

    # Now OME are using RHEL without Spacewalk, the current best-method of
    # checking `is server deployed in Dundee/SLS` is checking for the SLS nameservers.
    - role: ome.system_monitor_agent
      when: "'10.1.255.216' in ansible_dns.nameservers"

  handlers:
    - name: reload nginx
      listen: ssl certificate changed
      become: true
      service:
        name: nginx
        state: reloaded


  tasks:

    - name: Install open-vm-tools if system is a VMware vm
      become: yes
      yum:
        name: open-vm-tools
        state: present
      when: >
           ((ansible_virtualization_type is defined)
           and (ansible_virtualization_type == "VMware"))
           and not (molecule_test | default(False))

    # (Total cores / 2), leaving some for WSGI
    # post 2.3 'dest' should be renamed 'path'
    - name: NGINX - Performance tuning - worker processes
      become: yes
      replace:
        dest: "/etc/nginx/nginx.conf"
        regexp: '^worker_processes\s+\d+;'
        replace: "worker_processes {{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }};"

    # post 2.3 'dest' should be renamed 'path'
    # cf https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
    - name: NGINX - Performance tuning - worker connections
      become: yes
      replace:
        dest: "/etc/nginx/nginx.conf"
        regexp: 'worker_connections\s+\d+;'
        replace: "worker_connections 65000;"

    - name: NGINX - create nested includes directory
      become: yes
      file:
        path: /etc/nginx/conf.d-nested-includes
        state: directory

    - name: NGINX - SSL Configuration
      become: yes
      template:
        src: templates/nginx-confdnestedincludes-ssl-conf.j2
        dest: /etc/nginx/conf.d-nested-includes/ssl.conf
      notify:
        - restart nginx

    - name: NGINX - Custom Paper Redirect
      become: yes
      template:
        src: templates/nginx-confdnestedincludes-ns-pub-redirects-conf.j2
        dest: /etc/nginx/conf.d-nested-includes/ns-pub-redirects.conf
      notify:
        - restart nginx

  vars:
    omero_web_config_set_for_playbook:
      omero.web.nginx_server_extra_config:
        - 'include /etc/nginx/conf.d-nested-includes/*.conf;'
    omero_web_config_set: >-
      {{
        omero_web_config_set_for_playbook | combine(
        (omero_web_config_set_for_group | default({})),
        (omero_web_config_set_for_host | default({})))
      }}

    omero_web_release: "{{ omero_web_release_override | default('5.8.1') }}"
    omero_figure_release: "{{ omero_figure_release_override | default('4.3.2') }}"
    omero_fpbioimage_release: "{{ omero_fpbioimage_release_override | default('0.4.0') }}"
    omero_iviewer_release: "{{ omero_iviewer_release_override | default('0.10.1') }}"
    omero_parade_release: "{{ omero_parade_release_override | default('0.2.1') }}"
    omero_webtagging_autotag_release: "{{ omero_webtagging_autotag_release_override | default('3.1.0') }}"
    omero_webtagging_tagsearch_release: "{{ omero_webtagging_tagsearch_release_override | default('3.1.0') }}"

    omero_web_apps_names:
      - omero_figure
      - omero_fpbioimage
      - omero_iviewer
      - omero_parade
      - omero_webtagging_autotag
      - omero_webtagging_tagsearch

    omero_web_apps_packages:
      - "omero-figure=={{ omero_figure_release }}"
      - "omero-fpbioimage=={{ omero_fpbioimage_release }}"
      - "omero-iviewer=={{ omero_iviewer_release }}"
      - "omero-parade=={{ omero_parade_release }}"
      - "omero-webtagging-autotag=={{ omero_webtagging_autotag_release }}"
      - "omero-webtagging-tagsearch=={{ omero_webtagging_tagsearch_release }}"

    omero_web_apps_top_links:
      - label: Figure
        link: figure_index
        attrs:
          title: Open Figure in new tab
          target: _blank
      - label: Tag Search
        link: tagsearch

    omero_web_apps_config_append:
      omero.web.open_with:
        - - omero_figure
          - new_figure
          - supported_objects:
              - images
            target: _blank
            label: OMERO.figure
        - - omero_fpbioimage
          - fpbioimage_index
          - supported_objects:
              - image
            script_url: fpbioimage/openwith.js
            label: FPBioimage
        - - omero_iviewer
          - omero_iviewer_index
          - supported_objects:
              - images
              - dataset
              - well
            script_url: omero_iviewer/openwith.js
            label: OMERO.iviewer
      omero.web.ui.center_plugins:
        - - Auto Tag
          - omero_webtagging_autotag/auto_tag_init.js.html
          - auto_tag_panel
        - - Parade
          - omero_parade/init.js.html
          - omero_parade

    omero_web_apps_config_set:
      omero.web.viewer.view: omero_iviewer.views.index

    nginx_version: 1.18.0
    # Disable SSL combined certificate and key
    ssl_certificate_combined_path: ''
