---

- src: rvm_io.ruby
  version: v2.0.1

- src: openmicroscopy.jekyll-build
  version: 1.3.0

- src: openmicroscopy.lvm-partition
  version: 1.1.0

- src: openmicroscopy.network
  version: 1.0.0

- src: openmicroscopy.nginx-proxy
  version: 1.7.0

- src: openmicroscopy.nginx-ssl-selfsigned
  version: 1.0.0

- src: openmicroscopy.omero-common
  version: 0.1.0

- src: openmicroscopy.omego
  version: 0.1.1

- src: openmicroscopy.omero-server
  version: 2.0.2

- src: openmicroscopy.omero-web
  version: 1.0.1

- src: openmicroscopy.omero-user
  version: 0.1.1

- src: openmicroscopy.lvm-partition
  version: 1.1.0

- src: openmicroscopy.postgresql
  version: 2.0.0

- name: openmicroscopy.selinux-utils
  version: 1.0.3

- src: openmicroscopy.system-monitor-agent
  version: 0.1.0

- src: openmicroscopy.sudoers
  version: 1.0.0
