---

- name: ome.certbot
  src: https://github.com/ome/ansible-role-certbot/archive/0.1.0.tar.gz
  version: 0.1.0

- src: ome.cli_utils
  version: 1.1.0

- src: ome.deploy_archive
  version: 0.1.3

- src: ome.docker
  version: 3.0.2

- src: ome.ice
  version: 3.0.0

- src: ome.java
  version: 2.0.3

- name: ome.iptables_raw
  version: 0.2.1

- src: ome.lvm_partition
  version: 1.1.1

- name: ome.network
  version: 1.1.3

- src: ome.nginx
  version: 1.1.1

- src: ome.nginx_proxy
  version: 1.12.0

- src: ome.nfs_mount
  version: 1.2.1

- src: ome.omego
  version: 0.1.3

- src: ome.omero_common
  version: 0.1.0

- src: ome.basedeps
  version: 1.1.0

- src: ome.omero_prometheus_exporter
  version: 0.2.1

- src: ome.omero_python_deps
  version: 2.0.1

# https://github.com/ome/ansible-role-omero-server/pull/40
- name: ome.omero_server
  src: https://github.com/ome/ansible-role-omero-server/archive/5e26aa5c66c1b45ddbcd16151214ffcf024cff08.tar.gz
  version: 5e26aa5c66c1b45ddbcd16151214ffcf024cff08

- src: ome.omero_user
  version: 0.1.2

# https://github.com/ome/ansible-role-omero-web/pull/26
- name: ome.omero_web
  src: https://github.com/ome/ansible-role-omero-web/archive/b31b08897b28d35e2c657439925f920c13f96886.tar.gz
  version: b31b08897b28d35e2c657439925f920c13f96886

- src: ome.omero_web_apps
  version: 0.2.0

- src: ome.omero_web_django_prometheus
  version: 0.2.1

- src: ome.postgresql
  version: 3.3.1

- src: ome.postgresql_backup
  version: 0.1.1

- src: ome.prometheus
  version: 0.3.1

- src: ome.prometheus_jmx
  version: 0.2.1

- src: ome.prometheus_node
  version: 0.2.1

- src: ome.prometheus_postgres
  version: 0.2.1

- src: ome.redis
  version: 1.1.1

- name: ome.selinux_utils
  version: 1.0.3

- src: ome.ssl_certificate
  version: 0.3.2

- src: ome.sudoers
  version: 1.0.1

- src: ome.system_monitor_agent
  version: 0.1.1

- src: ome.upgrade_distpackages
  version: 1.1.1

- src: ome.versioncontrol_utils
  version: 1.0.2

- name: idr.idr-jupyter
  src: idr.ansible-role-idr-jupyter
  version: 3.0.0
