---
- src: ome.omero_common
- src: ome.basedeps
- src: ome.java
- src: ome.python3_virtualenv
- src: ome.ice
- src: ome.postgresql
- src: ome.postgresql_client
- src: ome.deploy_archive
- src: ome.omero_server
- src: ome.omero_web
- src: ome.nginx
- src: ome.redis
- src: ome.selinux_utils
- src: ome.versioncontrol_utils
- src: ome.ssl_certificate
- src: nfs_mount
- src: nfs_share
- src: iptables_raw
- src: ome.cli_utils
- src: ome.docker
- src: ome.postgresql_backup
- src: ome.omero_user
- src: ome.lvm_partition
