---

- src: rvm_io.ruby
  version: v2.0.1

- src: openmicroscopy.jekyll-build
  version: 1.3.1

- src: openmicroscopy.lvm-partition
  version: 1.1.0

- name: openmicroscopy.network
  version: 1.1.2

- src: openmicroscopy.nginx-proxy
  version: 1.8.0

- src: openmicroscopy.ssl-certificate
  version: 0.2.0

- src: openmicroscopy.nfs-mount
  version: 1.0.0

- src: openmicroscopy.omero-common
  version: 0.1.0

- src: openmicroscopy.omego
  version: 0.1.1

- src: openmicroscopy.omero-server
  version: 2.0.5

- src: openmicroscopy.omero-web
  version: 1.0.3

- src: openmicroscopy.omero-user
  version: 0.1.1

- src: openmicroscopy.docker
  version: 2.3.0

- src: openmicroscopy.lvm-partition
  version: 1.1.0

- src: openmicroscopy.postgresql
  version: 2.0.0

- name: openmicroscopy.postgresql-3
  src: openmicroscopy.postgresql
  version: 3.0.1

# https://github.com/openmicroscopy/ansible-role-prometheus/pull/5
- name: openmicroscopy.prometheus
  src: https://github.com/manics/ansible-role-prometheus/archive/fad82bea161a8145ec0029424684dc4837dce009.tar.gz
  version: fad82bea161a8145ec0029424684dc4837dce009

# https://github.com/openmicroscopy/ansible-role-prometheus-jmx/pull/2
- name: openmicroscopy.prometheus-jmx
  src: https://github.com/manics/ansible-role-prometheus-jmx/archive/4c83adca49816fe8333d8b912633160e79a3f444.tar.gz
  version: 4c83adca49816fe8333d8b912633160e79a3f444

# https://github.com/openmicroscopy/ansible-role-prometheus-node/pull/2
- name: openmicroscopy.prometheus-node
  src: https://github.com/manics/ansible-role-prometheus-node/archive/9b5fd284287f60d9be39bf8448c82f23d372f996.tar.gz
  version: 9b5fd284287f60d9be39bf8448c82f23d372f996

# https://github.com/openmicroscopy/ansible-role-prometheus-postgres/pull/3
- name: openmicroscopy.prometheus-postgres
  src: https://github.com/manics/ansible-role-prometheus-postgres/archive/8d26cfe3f21352b3023612095012400bdbd8efa9.tar.gz
  version: 8d26cfe3f21352b3023612095012400bdbd8efa9

- name: openmicroscopy.selinux-utils
  version: 1.0.3

- src: openmicroscopy.system-monitor-agent
  version: 0.1.0

- src: openmicroscopy.sudoers
  version: 1.0.0
