---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |    
    yamllint .
    ansible-lint
    flake8
  # TODO: enable
  enabled: False
platforms:
  - name: ome-dockr-prod1.openmicroscopy.org
    image: centos/systemd:latest
    command: /sbin/init
    privileged: true
    groups:
      - docker-hosts
      - omedev-docker
    published_ports:
      - "0.0.0.0:9090:9090/tcp"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  inventory:
    host_vars:
      ome-dockr-prod1.openmicroscopy.org:
        ome_monitored_node_exporter_hosts:
          - node.example.org
        ome_monitored_postgres_hosts:
          - pg.example.org
        ome_monitored_omero_server_hosts:
          - omeroserver.example.org
        ome_monitored_omero_web_hosts:
          - omeroweb.example.org
        prometheus_docker_data_volume: /srv/prometheus
        nfs_minio_data_volume: /srv/minio
        redmine_tracker_docker_data_volume: /srv/redmine-files

    group_vars:
      # all:
      #   molecule_test: True
      docker-hosts:
        # This should allow docker-in-docker to work
        docker_storage_driver: vfs
        # Latest version 17.12.1.ce-1.el7.centos has a bug that prevents
        # testing on travis: https://github.com/docker/for-linux/issues/219
        docker_version: 17.09.1.ce-1.el7.centos
  lint:
    name: ansible-lint
scenario:
  name: docker-prod
verifier:
  name: testinfra
  lint:
    name: flake8
