---
# tasks for omero-web
-
- include: pre_tasks.yml

- include: web-dependencies.yml

- include: web-install-py3.yml

- include: web-systemd.yml
  when: omero_web_systemd_setup

- include: web-nginx.yml
  when: omero_web_setup_nginx
