---

- ansible.builtin.import_role:
    name: ome.omero_common

- name: omero-web | Include ome.selinux_utils
  ansible.builtin.include_role:
    name: ome.selinux_utils

- name: omero-web | Include ome.python3_virtualenv role
  ansible.builtin.include_role:
    name: ome.python3_virtualenv

- name: omero-web | Include ome.nginx role
  ansible.builtin.include_role:
    name: ome.nginx
  when: omero_web_setup_nginx

- name: omero-web | Include ome.basedeps role
  ansible.builtin.include_role:
    name: ome.basedeps
