# Setup prometheus agents

- hosts: omero-server

  roles:

    - role: ome.prometheus_jmx

    - role: ome.prometheus_postgres
      prometheus_postgres_dbname: omero

    # For restart handlers
    - role: ome.omero_common

    - role: ome.omero_prometheus_exporter
      omero_prometheus_exporter_omero_user: >-
        "{{ secret_omero_prometheus_exporter_omero_user | default('root') }}"
      omero_prometheus_exporter_omero_password: >-
        "{{ secret_omero_prometheus_exporter_omero_password
        | default('omero') }}"

  tasks:

    - name: omero-server prometheus jmx agents
      become: true
      copy:
        dest: "{{ omero_common_basedir }}/server/config/prometheus.omero"
        src: omero-server-config-prometheus.omero
        mode: 0644
      notify:
        - restart omero-server


- hosts: omero-web

  roles:

    - role: ome.omero_web_django_prometheus


# NOTE: This assumes omero-web.conf is present and includes
# /etc/nginx/conf.d-nested-includes
- hosts: monitored

  roles:

    - role: ome.prometheus_node

  # Autodetect whether selinux is enabled
    - role: ome.selinux_utils

  tasks:

    - name: nginx selinux allow network connect
      become: true
      seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true
      when: selinux_enabled

    - name: Create monitoring htpasswd
      become: true
      copy:
        content: >-
          "{{ secret_monitoring_nginx_htpasswd |
          default(monitoring_nginx_htpasswd) }}"
        dest: /etc/nginx/monitoring.htpasswd
        mode: 0644

    # This is fine to apply to all servers because if an exporter doesn't
    # exist it will return an error, and we know which exporters to expect
    # when scraping
    - name: Create nginx proxy for prometheus exporters
      become: true
      copy:
        dest: /etc/nginx/conf.d-nested-includes/proxy-exporters.conf
        src: confd-nested-proxy-exporters.conf
        mode: 0644
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      become: true
      service:
        name: nginx
        state: restarted

  vars:
    # monitoring:monitoring
    monitoring_nginx_htpasswd: |
      monitoring:$apr1$njrafrtU$19wf/I15zPuSudlM5Y50Z0


- hosts: omero-web

  tasks:
    - name: Create nginx proxy for prometheus web exporters
      become: true
      copy:
        dest: /etc/nginx/conf.d-nested-includes/proxy-exporters-web.conf
        src: confd-nested-proxy-exporters-web.conf
        mode: 0644
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      become: true
      service:
        name: nginx
        state: restarted
