---

- name: python3 venv | install python3
  become: true
  apt:
    update_cache: true
    name:
      - python3
      - python3-distutils
      - python3-venv
      - python3-pip
      - python3-setuptools
    state: present
