---

- import_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'

- import_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'

- name: python3 venv | create python virtualenv wrapper
  become: true
  copy:
    dest: /usr/local/bin/ome-python3-virtualenv
    src: ome-python3-virtualenv.sh
    mode: 'u=rwx,g=rx,o=rx'
