# Install iproute for ansible network vars
- hosts: all
  tasks:
   - name: Install iproute
     become: true
     yum:
      name: iproute
      state: present

   - name: Install cron
     become: true
     yum:
      name: cronie
      state: present
