# Install iproute for ansible network vars
- name: Prepare iproute in resources
  hosts: all
  tasks:
   - name: Install iproute
     become: true
     ansible.builtin.dnf:
      name: iproute
      state: present

   - name: Install cron
     become: true
     ansible.builtin.dnf:
      name: cronie
      state: present
