---
# - name: system packages | add nginx apt key
#   become: true
#   ansible.builtin.apt_key:
#     keyring: /usr/share/keyrings/nginx-archive-keyring.gpg
#     url:  https://nginx.org/keys/nginx_signing.key
#     id: ABF5BD827BD9BF62


# - name: system packages | Add nginx stable repository into sources list
#   ansible.builtin.apt_repository:
#     repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu jammy nginx"
#     state: present

- name: system packages | install nginx
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present

- name: nginx | remove default config
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
