---
galaxy_info:
  role_name: nfs-mount

  author: Lucas Maurice (Sonic)
  description: Manage NFS mounts
  company: Justereseau

  license: WTFPL

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - 9
        - 10
    - name: Ubuntu
      versions:
        - 16.04
        - 18.04

  galaxy_tags:
    - nfs
    - share
    - nfs3
    - nfs4

dependencies: []
