---
- name: Include family related vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install NFS mount utility
  become: true
  package:
    name: "{{ nfs_package }}"
    state: present

# Do not create mountpoint using file, the mount module will create it
# automatically. This avoids problems where the module tries to change
# permissions on an existing directory

- name: Mount NFS share
  become: true
  mount:
    fstype: "{{ item.nfs_version | default(nfs_version) }}"
    name: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.location }}"
    state: mounted
  with_items: "{{ nfs_share_mounts }}"
