---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: java-jre
    image: rockylinux:9
  - name: java-jdk
    image: rockylinux:9
  - name: java-jre11
    image: rockylinux:9
  - name: java-jdk11
    image: rockylinux:9
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      java-jdk:
        java_jdk_install: true
      java-jre11:
        java_versions:
          - "11"
      java-jdk11:
        java_versions:
          - "11"
        java_jdk_install: true

scenario:
  name: rockylinux-9
verifier:
  name: testinfra
  directory: ../resources/tests/
