---
# tasks file for roles/java

- name: java | manage legacy java version
  block:

    - name: java | warn about old java_jre_versions variables
      ansible.builtin.fail:
        msg: java_jre_versions variable is deprecated, use java_versions instead
      ignore_errors: true

    - name: java | set java_versions from old java_jre_versions variables
      ansible.builtin.set_fact:
        java_versions: "{{ java_jre_versions }}"

  when: java_jre_versions is defined

- name: java | import tasks for redhat OS family
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'

- name: java | import tasks for debian OS family
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'
