---
# tasks file for roles/java

- name: system packages | install java jre (rockylinux)
  become: true
  ansible.builtin.dnf:
    name: >-
      java-{{ java_backwards_compatibility_version.redhat[item] |
      default(item) }}-openjdk
    state: present
  with_items: "{{ java_versions }}"

- name: system packages | install java jdk (rockylinux)
  become: true
  ansible.builtin.dnf:
    name: >-
      java-{{ java_backwards_compatibility_version.redhat[item] |
      default(item) }}-openjdk-devel
    state: present
  when: java_jdk_install
  with_items: "{{ java_versions }}"
