---
- name: Converge
  hosts: all
  become: true

  vars:
    pip_executable: pip
    pip_install_packages:
      - docker-compose
      - docker

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

  roles:
    - nfs-mount
