---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: omero-server-rockylinux9
    image: eniocarboni/docker-rockylinux-systemd:9
    image_version: latest
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
    groups:
      - docker-hosts
      - omero-py3
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  # To test the upgrade process without breaking the idempotence check
  # - install omero during the prepare step which is only run once
  # - attempt to upgrade in the converge step
  options:
    v: true
    diff: true
    # tags: [x]
  playbooks:
    # TODO: Use shared test playbooks
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      omero-server-rockylinux9:
        postgresql_version: "13"
        omero_server_selfsigned_certificates: true
scenario:
  name: rockylinux9
  converge_sequence:
    - converge

verifier:
  name: testinfra
  directory: ../resources/tests/
