---

- name: Postgres | install gpg for apt repo
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: gnupg
    state: present

- name: Postgres | get postgresql apt key
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Postgres | setup apt repo
  become: true
  ansible.builtin.apt_repository:
    codename: "{{ ansible_distribution_release }}"
    repo: deb http://apt.postgresql.org/pub/repos/apt/
          {{ ansible_distribution_release }}-pgdg main

- name: Postgres | install client packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: postgresql-client-{{ postgresql_version }}
    state: present
