---

- name: Import tasks for redhat
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family | lower == 'redhat'

- name: Import tasks for debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family | lower == 'debian'
