---
galaxy_info:
  role_name: versioncontrol_utils
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Utilities for managing source code
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 9
  namespace: ome
  galaxy_tags: []

dependencies: []
