---
# vars file for ome.postgresql_client

# DEPRECATED
# This variable includes information used by the postgresql (server) role
postgresql_distribution_redhat:
  "12":
    repo: pgdg12
    basename: postgresql12
    setup: postgresql-12-setup
  "13":
    repo: pgdg13
    basename: postgresql13
    setup: postgresql-13-setup
  "14":
    repo: pgdg14
    basename: postgresql14
    setup: postgresql-14-setup
  "15":
    repo: pgdg15
    basename: postgresql15
    setup: postgresql-15-setup
  "16":
    repo: pgdg16
    basename: postgresql16
    setup: postgresql-16-setup
