---
galaxy_info:
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Useful command-line utilities for administering a server
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.10
  platforms:
    - name: EL
      versions:
        - 9
  namespace: ome
  role_name: cli_utils
  galaxy_tags: []
