---

- name: zeroc ice | Include ome.basedeps role
  include_role:
    name: ome.basedeps
  when: >-
    (ansible_os_family | lower == 'redhat') and
    (ansible_distribution_major_version == '9')

- name: zeroc ice | Include ome.java
  include_role:
    name: ome.java
  when: >-
    (ansible_os_family | lower == 'redhat') and
    (ansible_distribution_major_version == '9')


- name: zeroc ice | Include ome.jadeploy_archiveva debian
  include_role:
    name: ome.deploy_archive
  vars:
    ansible_become: yes
    deploy_archive_dest_dir: /opt
    deploy_archive_src_url: "https://github.com/\
   glencoesoftware/zeroc-ice-ubuntu2204-x86_64/releases/\
   download/{{ ice_zeroc_ice_ubuntu2204_version }}/Ice-3.6.5-ubuntu2204-x86_64.tar.gz"
    deploy_archive_sha256: "{{ ice_zeroc_ice_ubuntu2204_sha256 }}"
    deploy_archive_symlink: /opt/ice
    deploy_archive_internal_root: >-
      Ice-3.6.5
  when: >-
      (ansible_os_family | lower == 'debian') and
      (ansible_distribution_major_version == '22')


- name: zeroc ice | Include ome.jadeploy_archiveva redhat
  include_role:
      name: ome.deploy_archive
  vars:
    ansible_become: yes
    deploy_archive_dest_dir: /opt
    deploy_archive_src_url: "https://github.com/\
glencoesoftware/zeroc-ice-rhel9-x86_64/releases/\
download/{{ ice_zeroc_ice_rockylinux9_version }}/Ice-3.6.5-rhel9-x86_64.tar.gz"
    deploy_archive_sha256: "{{ ice_zeroc_ice_rockylinux9_sha256 }}"
    deploy_archive_symlink: /opt/ice
    deploy_archive_internal_root: >-
      Ice-3.6.5
  when: >-
        (ansible_os_family | lower == 'redhat') and
        (ansible_distribution_major_version == '9')
