---
# tasks file for roles/ice



#- name: zeroc ice | set-enabled crb
#  become: true
#  ansible.builtin.command: dnf config-manager --set-enabled crb
#  state: present

- name : zeroc ice | check rocky.repo file
  stat:
    path: /etc/yum.repos.d/rocky.repo
  register: rockyrepo_name

- name: zeroc ice | install config-manager in rocky
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - 'dnf-command(config-manager)'
    state: present
  when: rockyrepo_name.stat.exists

- name: zeroc ice | Enable crp repo in rocky
  become: true
  ansible.builtin.replace:
    path:  /etc/yum.repos.d/rocky.repo
    # create: false
    regexp: enabled=0
    replace: enabled=1
    # state: present
  when: rockyrepo_name.stat.exists

- name: zeroc ice | Add CRB repository for RHEL
  become: true
  ansible.builtin.command:
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms
  when: ansible_os_family == 'RedHat' and not rockyrepo_name.stat.exists

- name: zeroc ice | install libdb
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - libdb-cxx
    state: present

# - name: zeroc ice | command echo lib64
#   ansible.builtin.command: echo /opt/ice-3.6.5/lib64 > /etc/ld.so.conf.d/ice-x86_64.conf
#   become: true

# - name: zeroc ice | command ldconfig
#   ansible.builtin.command: ldconfig
#   become: true

- name: zero ice | install python
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: python
    state: present

- name: zeroc ice | install ice pip dependencies
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - gcc
      - gcc-c++
      - libdb-utils
      - bzip2-devel
      - expat-devel
      - openssl-devel
      - python-devel
      - python-pip
    state: present
  when: ice_install_python and (ice_python_wheel | length < 1)

- name: zeroc ice | pip install packages
  become: true
  pip:
    name:
      - "zeroc-ice>=3.6,<3.7"
    state: present
  when: ice_install_python and (ice_python_wheel | length < 1)

- name: zeroc ice | install python-pip for wheel
  become: true
  yum:
    name: python-pip
    state: present
  when: ice_install_python and (ice_python_wheel | length >= 1)

- name: zeroc ice | install ice wheel package
  become: true
  pip:
    name: "{{ ice_python_wheel }}"
    state: present
  when: ice_install_python and (ice_python_wheel | length >= 1)
