---
# tasks file for roles/basedeps
- name: Import a key for epel
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  when: ansible_os_family == 'RedHat'

- name: epel | setup dnf repository
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat'

# use separate yum/apt tasks because package only installs one item at a time
- name: system packages | basic system utils (rockylinux)
  become: true
  ansible.builtin.dnf:
    name: "{{ basedeps_packages.redhat }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: system packages | basic system utils (ubuntu)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ basedeps_packages.debian }}"
    state: present
  when: ansible_os_family == 'Debian'
