---
# tasks file for roles/versioncontrol-utils

- name: system packages | install epel repo
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: epel-release
    state: present

- name: system packages | basic system utils
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - git
