---
# Playbook for maintaining OME production web proxies

- hosts: web-proxies
  roles:
    - role: ome.network
      tags: network
    - role: ome.lvm_partition
      tags: lvm
      lvm_lvname: root
      lvm_lvmount: /
      lvm_lvsize: "{{ root_size }}"
      lvm_lvfilesystem: "{{ root_filesystem }}"
    - role: ome.lvm_partition
      tags: lvm
      lvm_lvname: var_log
      lvm_lvmount: /var/log
      lvm_lvsize: "{{ varlog_size }}"
      lvm_lvfilesystem: "{{ root_filesystem }}"
    - role: ome.ssl_certificate
    - role: ome.nginx_proxy

  handlers:
    - name: reload nginx
      listen: ssl certificate changed
      become: true
      service:
        name: nginx
        state: reloaded

  vars:
    nginx_version: 1.18.0
