---
# defaults file for ice

ice_install_devel: true
ice_install_python: true
ice_python_wheel: ''

# Symlink the main ice binaries into this directory
ice_binaries_symlink_dest: ''


######################################################################
# Expert users only!
######################################################################

ice_zeroc_ice_ubuntu2204_version: '20221004'
ice_zeroc_ice_ubuntu2204_sha256: >-
  05e5148f7df0dfc6f06ee2e4445419f95d5b19e4fc8c99660d93af13fb14e709

ice_zeroc_ice_rockylinux9_version: '20231130'
ice_zeroc_ice_rockylinux9_sha256: >-
  9da10544e46dc95197e670dda4df18200d80991c404b2a2692d635ab59896c5d
