galaxy_info:
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Manage NFS file shares
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.1
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []

dependencies: []
