---
- name: Permissions
  hosts: idr0-slot3.openmicroscopy.org
  become: true
  tasks:
    - name: Set perms /uod/idr/www
      ansible.builtin.file:
        path: /uod/idr/www
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Set perms2
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items: "{{ www_folders }}"

    - name: Set perms3 www_folders
      ansible.builtin.find:
        paths: "{{ www_folders }}"
        file_type: "directory"
        recurse: "no"
      register: "products"

    - name: Set perms3
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: lsd
        mode: 01775
      with_items: "{{ products.files | map(attribute='path') | list }}"
