---
- hosts: idr0-slot3.openmicroscopy.org
  become: true
  tasks:
    - name: set perms /uod/idr/www
      file:
        path: /uod/idr/www
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: set perms2
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items: "{{ www_folders }}"

    - name: set perms3 www_folders
      find:
        paths: "{{ www_folders }}"
        file_type: "directory"
        recurse: "no"
      register: "products"

    - name: set perms3
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: lsd
        mode: 01775
      with_items: "{{ products.files | map(attribute='path') | list }}"
