---
- hosts: idr0-slot3.openmicroscopy.org
  become: true
  tasks:
    - name: update presentations
      git:
        repo: https://github.com/ome/presentations
        force: no
        update: yes
        dest: "/uod/idr/www/downloads.openmicroscopy.org/presentations"
