---
# k.h.gillen@dundee.ac.uk Mon 15 Oct 2018 11:11:42 BST

# Playbook which deploys SSL certificates to legacy
# (not entirely Ansible managed) hosts

# openmicroscopy.org wildcard
- hosts: legacy-ssl-org-wildcard
  roles:
  - role: ome.ssl_certificate
    # See private vars for certificate content
    # Server path to SSL public certificate
    ssl_certificate_public_path: /etc/pki/tls/certs/star_openmicroscopy_org.crt
    # Server path to SSL intermediate certificate(s)
    ssl_certificate_intermediate_path: /etc/pki/tls/certs/star_openmicroscopy_org.chain
    # Server path to SSL bundled public and intermediate certificates
    ssl_certificate_bundled_path: /etc/pki/tls/certs/star_openmicroscopy_org.crt+bundle
    # Server path to SSL certificate key
    ssl_certificate_key_path: /etc/pki/tls/private/star_openmicroscopy_org.key
    # Server path to SSL combined certificate and key, set to empty to disable
    ssl_certificate_combined_path: ''





#Adding a new pull request
