---
- name: Converge
  hosts: all
  roles:
    - role: ome.iptables_raw

  tasks:
    # - allow established/related inbound/outbound
    # - allow ssh inbound
    # - block http outbound
    # - allow all other outbound
    - name: Create iptables test rules
      iptables_raw_25:
        name: test_rules
        keep_unmanaged: false
        rules: |
          -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
          -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
          -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
          -A OUTPUT -p tcp -m tcp --dport 80 -j REJECT
          -A INPUT -j REJECT
          -A FORWARD -j REJECT
          -A OUTPUT -j ACCEPT
        state: present

# TODO: For a full test we should reboot and check the iptables rules
# are still active
