# Workaround lack of cron on Docker
- name: Prepare pg prod
  hosts: ome-pg-prod1.openmicroscopy.org
  tasks:
   - name: Install cron
     become: true
     ansible.builtin.dnf:
      name: cronie
      state: present
