---
- name: Converge
  hosts: all
  roles:
    - role: ome.python3_virtualenv

  tasks:
    - name: test | upgrade pip
      become: true
      pip:
        name: "pip>=21"
        state: present
        virtualenv: /opt/test/python3-virtualenv
        virtualenv_command: /usr/local/bin/ome-python3-virtualenv

    - name: test | install packages
      become: true
      pip:
        name:
          - omego
          - scc
        state: present
        virtualenv: /opt/test/python3-virtualenv
        virtualenv_command: /usr/local/bin/ome-python3-virtualenv
