---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: postgresql12
    image: rockylinux:9
  - name: postgresql13
    image: rockylinux:9
  - name: postgresql14
    image: rockylinux:9
  - name: postgresql15
    image: rockylinux:9
  - name: postgresql16
    image: rockylinux:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      postgresql_exact:
      postgresql12:
        postgresql_version: "12"
      postgresql13:
        postgresql_version: "13"
      postgresql14:
        postgresql_version: "14"
      postgresql15:
        postgresql_version: "15"
      postgresql16:
        postgresql_version: "16"
  playbooks:
    converge: ../resources/playbook.yml
scenario:
  name: rockylinux9
verifier:
  name: testinfra
  directory: ../resources/tests/
