---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: rockylinux
    image: rockylinux:9
  - name: ubuntu-22.04
    image: ubuntu:22.04
  - name: ubuntu-systemd-22.04
    image: eniocarboni/docker-ubuntu-systemd:22.04
  - name: rockylinux-systemd-22.04
    image: eniocarboni/docker-rockylinux-systemd:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
