---
name: Molecule
# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:

  list-scenarios:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.listscenarios.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
      - id: listscenarios
        uses: ome/action-ansible-molecule-list-scenarios@main

  test:
    name: Test
    needs:
      - list-scenarios
    runs-on: ubuntu-20.04
    strategy:
      # Keep running so we can see if other tests pass
      fail-fast: false
      matrix:
        scenario: ${{fromJson(needs.list-scenarios.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Ansible & Molecule
        run: |
            pip install "ansible<8" ansible-lint flake8
            pip install "molecule<5" "ansible-compat<4"
            pip install molecule-plugins[docker] pytest-testinfra
      - name: Run molecule
        run: molecule test -s "${{ matrix.scenario }}"
